### ISSUE TITLE
Highlight js is removing the indentation when displayed 

### ISSUE THREAD

**Issue by BrianC24** [wcoder/highlightjs-line-numbers.js#23]

**Comment by TheEvilSocks** [comment]
This snippet of css should fix it.
```css
td.hljs-ln-code {
	white-space: pre-wrap;
}
```
