### ISSUE TITLE
Got wrong line numbers

### ISSUE THREAD

**Issue by david30xie** [wcoder/highlightjs-line-numbers.js#4]
Check this: http://preview.daimaduan.com/paste/f4612fa76b

line number shows 16, but actual line number is 19. I understand it's because highlightjs auto wrap words and lines, but how to make them match?

**Comment by wcoder** [comment]
Hi,
Currently script does not supported line wrapping.
Your using default styles from bootstrap for `pre` & `code`.

I suggest this CSS for fix your issue:
```css
pre {
	overflow: auto;
	word-break: normal;
	word-wrap: normal;
}
pre code {
	white-space: pre;
}
```
Best regards,
Yauheni
